[project]
name = "cdx-view-registry"
version = "0.1.0"
description = "CLI for registering and preprocessing datasets for cdx-view"
requires-python = ">=3.10,<3.11"
dependencies = [
    "numpy",
    "xarray",
    "netCDF4",
    "zarr",
    "rioxarray",
    "rasterio",
    "dask",
    "morecantile",
    "xwrf",
    "pytz",
    "rio-cogeo",
    "memray",
]

[dependency-groups]
dev = ["pytest"]

[tool.uv]
package = false
environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'darwin'",
]
